// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  pingP50: __t.u16().name("ping_p_50"),
  pingP95: __t.u16().name("ping_p_95"),
  worstP95: __t.u16().name("worst_p_95"),
  correctionsPerMin: __t.f32().name("corrections_per_min"),
  measuredMinutes: __t.f32().name("measured_minutes"),
  lastAt: __t.timestamp().name("last_at"),
});
