// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  room: __t.u8(),
  code: __t.string(),
  mapId: __t.string().name("map_id"),
  mode: __t.string(),
  size: __t.u8(),
  humans: __t.u32(),
  bots: __t.u32(),
  round: __t.u32(),
  phase: __t.string(),
});
