// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  onlineNow: __t.u32().name("online_now"),
  rooms: __t.u32(),
  humansInRooms: __t.u32().name("humans_in_rooms"),
  totalPlayers: __t.u32().name("total_players"),
  profiles: __t.u32(),
  playerMatches: __t.u32().name("player_matches"),
  roundsPlayed: __t.u32().name("rounds_played"),
  kills: __t.u32(),
  admins: __t.u32(),
});
