// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  name: __t.string(),
  firstSeen: __t.timestamp().name("first_seen"),
  lastSeen: __t.timestamp().name("last_seen"),
  sessions: __t.u32(),
  tz: __t.string(),
  lang: __t.string(),
  matches: __t.u32(),
  kills: __t.u32(),
});
