// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  age: __t.f32(),
  owner: __t.i32(),
  team: __t.i8(),
  hp: __t.f32(),
  timer: __t.f32(),
});
