// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  weapon: __t.u8(),
  ox: __t.f32(),
  oy: __t.f32(),
  oz: __t.f32(),
  dx: __t.f32(),
  dy: __t.f32(),
  dz: __t.f32(),
  target: __t.i32(),
  zone: __t.string(),
  px: __t.f32(),
  py: __t.f32(),
  pz: __t.f32(),
};
