// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdminLoginReducer from "./admin_login_reducer";
import AdminLogoutReducer from "./admin_logout_reducer";
import AdminRevokeAllReducer from "./admin_revoke_all_reducer";
import BuyReducer from "./buy_reducer";
import BuyAttachmentReducer from "./buy_attachment_reducer";
import ChangeTeamReducer from "./change_team_reducer";
import CreateRoomReducer from "./create_room_reducer";
import DeviceReducer from "./device_reducer";
import EnterVehicleReducer from "./enter_vehicle_reducer";
import ExitVehicleReducer from "./exit_vehicle_reducer";
import FireReducer from "./fire_reducer";
import GrenadeReducer from "./grenade_reducer";
import HelloReducer from "./hello_reducer";
import JoinReducer from "./join_reducer";
import JoinPublicReducer from "./join_public_reducer";
import JoinRoomReducer from "./join_room_reducer";
import LeaveReducer from "./leave_reducer";
import NetStatsReducer from "./net_stats_reducer";
import QuickAnyReducer from "./quick_any_reducer";
import QuickJoinReducer from "./quick_join_reducer";
import QuickPlayReducer from "./quick_play_reducer";
import ReloadWeaponReducer from "./reload_weapon_reducer";
import ReportReducer from "./report_reducer";
import SayReducer from "./say_reducer";
import StartRoomReducer from "./start_room_reducer";
import SwitchSlotReducer from "./switch_slot_reducer";
import UseCrateReducer from "./use_crate_reducer";
import VehicleReportReducer from "./vehicle_report_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AdminDailyRow from "./admin_daily_table";
import AdminDailyNetRow from "./admin_daily_net_table";
import AdminDailyTimeRow from "./admin_daily_time_table";
import AdminOverviewRow from "./admin_overview_table";
import AdminPlayerDeviceRow from "./admin_player_device_table";
import AdminPlayerNetRow from "./admin_player_net_table";
import AdminPlayerTimeRow from "./admin_player_time_table";
import AdminPlayersRow from "./admin_players_table";
import AdminRoomsRow from "./admin_rooms_table";
import AdminStatusRow from "./admin_status_table";
import BodyRow from "./body_table";
import FrameRow from "./frame_table";
import MatchRow from "./match_table";
import MatchEventRow from "./match_event_table";
import MyRoomCodeRow from "./my_room_code_table";
import PlayerRow from "./player_table";
import PointRow from "./point_table";
import PrivateRoomRow from "./private_room_table";
import ProfileRow from "./profile_table";
import RosterRow from "./roster_table";
import SoldierRow from "./soldier_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  body: __table({
    name: 'body',
    indexes: [
      { accessor: 'id', name: 'body_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'body_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BodyRow),
  frame: __table({
    name: 'frame',
    indexes: [
      { accessor: 'id', name: 'frame_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'frame_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FrameRow),
  match: __table({
    name: 'match',
    indexes: [
      { accessor: 'id', name: 'match_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchRow),
  matchEvent: __table({
    name: 'match_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, MatchEventRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  point: __table({
    name: 'point',
    indexes: [
      { accessor: 'id', name: 'point_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'point_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PointRow),
  privateRoom: __table({
    name: 'private_room',
    indexes: [
      { accessor: 'room', name: 'private_room_room_idx_btree', algorithm: 'btree', columns: [
        'room',
      ] },
    ],
    constraints: [
      { name: 'private_room_room_key', constraint: 'unique', columns: ['room'] },
    ],
  }, PrivateRoomRow),
  profile: __table({
    name: 'profile',
    indexes: [
      { accessor: 'identity', name: 'profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ProfileRow),
  roster: __table({
    name: 'roster',
    indexes: [
      { accessor: 'id', name: 'roster_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'room', name: 'roster_room_idx_btree', algorithm: 'btree', columns: [
        'room',
      ] },
    ],
    constraints: [
      { name: 'roster_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RosterRow),
  soldier: __table({
    name: 'soldier',
    indexes: [
      { accessor: 'id', name: 'soldier_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'soldier_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SoldierRow),
  adminDaily: __table({
    name: 'admin_daily',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminDailyRow),
  adminDailyNet: __table({
    name: 'admin_daily_net',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminDailyNetRow),
  adminDailyTime: __table({
    name: 'admin_daily_time',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminDailyTimeRow),
  adminOverview: __table({
    name: 'admin_overview',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminOverviewRow),
  adminPlayerDevice: __table({
    name: 'admin_player_device',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminPlayerDeviceRow),
  adminPlayerNet: __table({
    name: 'admin_player_net',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminPlayerNetRow),
  adminPlayerTime: __table({
    name: 'admin_player_time',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminPlayerTimeRow),
  adminPlayers: __table({
    name: 'admin_players',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminPlayersRow),
  adminRooms: __table({
    name: 'admin_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminRoomsRow),
  adminStatus: __table({
    name: 'admin_status',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminStatusRow),
  myRoomCode: __table({
    name: 'my_room_code',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRoomCodeRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("admin_login", AdminLoginReducer),
  __reducerSchema("admin_logout", AdminLogoutReducer),
  __reducerSchema("admin_revoke_all", AdminRevokeAllReducer),
  __reducerSchema("buy", BuyReducer),
  __reducerSchema("buy_attachment", BuyAttachmentReducer),
  __reducerSchema("change_team", ChangeTeamReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("device", DeviceReducer),
  __reducerSchema("enter_vehicle", EnterVehicleReducer),
  __reducerSchema("exit_vehicle", ExitVehicleReducer),
  __reducerSchema("fire", FireReducer),
  __reducerSchema("grenade", GrenadeReducer),
  __reducerSchema("hello", HelloReducer),
  __reducerSchema("join", JoinReducer),
  __reducerSchema("join_public", JoinPublicReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("leave", LeaveReducer),
  __reducerSchema("net_stats", NetStatsReducer),
  __reducerSchema("quick_any", QuickAnyReducer),
  __reducerSchema("quick_join", QuickJoinReducer),
  __reducerSchema("quick_play", QuickPlayReducer),
  __reducerSchema("reload_weapon", ReloadWeaponReducer),
  __reducerSchema("report", ReportReducer),
  __reducerSchema("say", SayReducer),
  __reducerSchema("start_room", StartRoomReducer),
  __reducerSchema("switch_slot", SwitchSlotReducer),
  __reducerSchema("use_crate", UseCrateReducer),
  __reducerSchema("vehicle_report", VehicleReportReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

