// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  mapId: __t.string().name("map_id"),
  phase: __t.string(),
  phaseLeft: __t.f64().name("phase_left"),
  time: __t.f64(),
  worldTime: __t.f64().name("world_time"),
  tick: __t.u32(),
  score0: __t.u32().name("score_0"),
  score1: __t.u32().name("score_1"),
  scoreTimer: __t.f64().name("score_timer"),
  lawsJson: __t.string().name("laws_json"),
  lawAuthor: __t.i32().name("law_author"),
  lawText: __t.string().name("law_text"),
  lawLeft: __t.f64().name("law_left"),
  rewindLeft: __t.u32().name("rewind_left"),
  nextId: __t.u32().name("next_id"),
  droneTimer: __t.f64().name("drone_timer"),
  winner: __t.i8(),
  configJson: __t.string().name("config_json"),
  historyHead: __t.u32().name("history_head"),
  historyLength: __t.u32().name("history_length"),
  lastTickMicros: __t.u64().name("last_tick_micros"),
  humans: __t.u32(),
  code: __t.string(),
});
