// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  kills: __t.u32(),
  deaths: __t.u32(),
  assists: __t.u32(),
  headshots: __t.u32(),
  roundsWon: __t.u32().name("rounds_won"),
  roundsPlayed: __t.u32().name("rounds_played"),
  matchesWon: __t.u32().name("matches_won"),
  matchesPlayed: __t.u32().name("matches_played"),
});
