// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  team: __t.u8(),
  bot: __t.bool(),
  alive: __t.bool(),
  grenades: __t.u8(),
  grenadeHe: __t.bool().name("grenade_he"),
  kills: __t.u32(),
  deaths: __t.u32(),
  assists: __t.u32(),
  score: __t.u32(),
  lastAttacker: __t.i32().name("last_attacker"),
  corrections: __t.u32(),
  weapon0: __t.string().name("weapon_0"),
  weapon1: __t.string().name("weapon_1"),
  reserve0: __t.u16().name("reserve_0"),
  reserve1: __t.u16().name("reserve_1"),
  money: __t.u32(),
  gearJson: __t.string().name("gear_json"),
});
