// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const PlayerState = __t.object("PlayerState", {
  identity: __t.identity(),
  lawsJson: __t.string(),
  latestCommandJson: __t.string(),
  historyJson: __t.string(),
  commandCount: __t.u32(),
  sessions: __t.u32(),
  scoreReports: __t.u32(),
  lastReportedScore: __t.u32(),
  bestReportedScore: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type PlayerState = __Infer<typeof PlayerState>;

