// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type Admin = __Infer<typeof Admin>;

export const AdminAttempt = __t.object("AdminAttempt", {
  identity: __t.identity(),
  windowStart: __t.timestamp(),
  failures: __t.u32(),
});
export type AdminAttempt = __Infer<typeof AdminAttempt>;

export const AdminDaily = __t.object("AdminDaily", {});
export type AdminDaily = __Infer<typeof AdminDaily>;

export const AdminDailyNet = __t.object("AdminDailyNet", {});
export type AdminDailyNet = __Infer<typeof AdminDailyNet>;

export const AdminDailyTime = __t.object("AdminDailyTime", {});
export type AdminDailyTime = __Infer<typeof AdminDailyTime>;

export const AdminDayNetRow = __t.object("AdminDayNetRow", {
  day: __t.u32(),
  date: __t.string(),
  players: __t.u32(),
  medianP50: __t.u16(),
  medianP95: __t.u16(),
  correctionsPerMin: __t.f32(),
});
export type AdminDayNetRow = __Infer<typeof AdminDayNetRow>;

export const AdminDayRow = __t.object("AdminDayRow", {
  day: __t.u32(),
  date: __t.string(),
  newPlayers: __t.u32(),
  activePlayers: __t.u32(),
});
export type AdminDayRow = __Infer<typeof AdminDayRow>;

export const AdminDayTimeRow = __t.object("AdminDayTimeRow", {
  day: __t.u32(),
  date: __t.string(),
  playSeconds: __t.u64(),
});
export type AdminDayTimeRow = __Infer<typeof AdminDayTimeRow>;

export const AdminOverview = __t.object("AdminOverview", {});
export type AdminOverview = __Infer<typeof AdminOverview>;

export const AdminOverviewRow = __t.object("AdminOverviewRow", {
  onlineNow: __t.u32(),
  rooms: __t.u32(),
  humansInRooms: __t.u32(),
  totalPlayers: __t.u32(),
  profiles: __t.u32(),
  playerMatches: __t.u32(),
  roundsPlayed: __t.u32(),
  kills: __t.u32(),
  admins: __t.u32(),
});
export type AdminOverviewRow = __Infer<typeof AdminOverviewRow>;

export const AdminPlayerNet = __t.object("AdminPlayerNet", {});
export type AdminPlayerNet = __Infer<typeof AdminPlayerNet>;

export const AdminPlayerNetRow = __t.object("AdminPlayerNetRow", {
  id: __t.string(),
  pingP50: __t.u16(),
  pingP95: __t.u16(),
  worstP95: __t.u16(),
  correctionsPerMin: __t.f32(),
  measuredMinutes: __t.f32(),
  lastAt: __t.timestamp(),
});
export type AdminPlayerNetRow = __Infer<typeof AdminPlayerNetRow>;

export const AdminPlayerRow = __t.object("AdminPlayerRow", {
  id: __t.string(),
  name: __t.string(),
  firstSeen: __t.timestamp(),
  lastSeen: __t.timestamp(),
  sessions: __t.u32(),
  tz: __t.string(),
  lang: __t.string(),
  matches: __t.u32(),
  kills: __t.u32(),
});
export type AdminPlayerRow = __Infer<typeof AdminPlayerRow>;

export const AdminPlayerTime = __t.object("AdminPlayerTime", {});
export type AdminPlayerTime = __Infer<typeof AdminPlayerTime>;

export const AdminPlayerTimeRow = __t.object("AdminPlayerTimeRow", {
  id: __t.string(),
  rounds: __t.u32(),
  playSeconds: __t.u64(),
  playingSince: __t.timestamp(),
});
export type AdminPlayerTimeRow = __Infer<typeof AdminPlayerTimeRow>;

export const AdminPlayers = __t.object("AdminPlayers", {});
export type AdminPlayers = __Infer<typeof AdminPlayers>;

export const AdminRoomRow = __t.object("AdminRoomRow", {
  room: __t.u8(),
  code: __t.string(),
  mapId: __t.string(),
  mode: __t.string(),
  size: __t.u8(),
  humans: __t.u32(),
  bots: __t.u32(),
  round: __t.u32(),
  phase: __t.string(),
});
export type AdminRoomRow = __Infer<typeof AdminRoomRow>;

export const AdminRooms = __t.object("AdminRooms", {});
export type AdminRooms = __Infer<typeof AdminRooms>;

export const AdminStatus = __t.object("AdminStatus", {});
export type AdminStatus = __Infer<typeof AdminStatus>;

export const AdminStatusRow = __t.object("AdminStatusRow", {
  admin: __t.bool(),
  failures: __t.u32(),
  windowStart: __t.timestamp(),
});
export type AdminStatusRow = __Infer<typeof AdminStatusRow>;

export const Body = __t.object("Body", {
  id: __t.u32(),
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  age: __t.f32(),
  owner: __t.i32(),
  team: __t.i8(),
  hp: __t.f32(),
  timer: __t.f32(),
  room: __t.u8(),
});
export type Body = __Infer<typeof Body>;

export const BotBrain = __t.object("BotBrain", {
  id: __t.u32(),
  json: __t.string(),
});
export type BotBrain = __Infer<typeof BotBrain>;

export const Clock = __t.object("Clock", {
  id: __t.u8(),
  phaseLeft: __t.f64(),
  time: __t.f64(),
  tick: __t.u32(),
  nextId: __t.u32(),
  lastTickMicros: __t.u64(),
  roundJson: __t.string(),
});
export type Clock = __Infer<typeof Clock>;

export const Command = __t.object("Command", {
  id: __t.u64(),
  soldierId: __t.u32(),
  json: __t.string(),
});
export type Command = __Infer<typeof Command>;

export const Counter = __t.object("Counter", {
  id: __t.u8(),
  nextId: __t.u32(),
});
export type Counter = __Infer<typeof Counter>;

export const Frame = __t.object("Frame", {
  id: __t.u8(),
  mapId: __t.string(),
  data: __t.byteArray(),
});
export type Frame = __Infer<typeof Frame>;

export const History = __t.object("History", {
  slot: __t.u32(),
  json: __t.string(),
});
export type History = __Infer<typeof History>;

export const Inbox = __t.object("Inbox", {
  soldierId: __t.u32(),
  lastMicros: __t.u64(),
  elapsed: __t.f32(),
  pending: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  crouch: __t.f32(),
  grounded: __t.bool(),
  sprint: __t.bool(),
  ads: __t.bool(),
  slide: __t.bool(),
  weapon: __t.u8(),
  use: __t.bool(),
});
export type Inbox = __Infer<typeof Inbox>;

export const Match = __t.object("Match", {
  id: __t.u8(),
  mapId: __t.string(),
  phase: __t.string(),
  phaseLeft: __t.f64(),
  time: __t.f64(),
  worldTime: __t.f64(),
  tick: __t.u32(),
  score0: __t.u32(),
  score1: __t.u32(),
  scoreTimer: __t.f64(),
  lawsJson: __t.string(),
  lawAuthor: __t.i32(),
  lawText: __t.string(),
  lawLeft: __t.f64(),
  rewindLeft: __t.u32(),
  nextId: __t.u32(),
  droneTimer: __t.f64(),
  winner: __t.i8(),
  configJson: __t.string(),
  historyHead: __t.u32(),
  historyLength: __t.u32(),
  lastTickMicros: __t.u64(),
  humans: __t.u32(),
  code: __t.string(),
});
export type Match = __Infer<typeof Match>;

export const MatchEvent = __t.object("MatchEvent", {
  seq: __t.u32(),
  json: __t.string(),
  room: __t.u8(),
});
export type MatchEvent = __Infer<typeof MatchEvent>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  soldierId: __t.u32(),
  lastReportMicros: __t.u64(),
  chatWindowMicros: __t.u64(),
  chatCount: __t.u32(),
  room: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const PlayerDay = __t.object("PlayerDay", {
  key: __t.string(),
  day: __t.u32(),
  identity: __t.identity(),
});
export type PlayerDay = __Infer<typeof PlayerDay>;

export const PlayerDayNet = __t.object("PlayerDayNet", {
  key: __t.string(),
  day: __t.u32(),
  identity: __t.identity(),
  reports: __t.u32(),
  seconds: __t.u32(),
  p50Sum: __t.f64(),
  p95Sum: __t.f64(),
  corrections: __t.u32(),
});
export type PlayerDayNet = __Infer<typeof PlayerDayNet>;

export const PlayerDayTime = __t.object("PlayerDayTime", {
  key: __t.string(),
  day: __t.u32(),
  identity: __t.identity(),
  seconds: __t.u32(),
});
export type PlayerDayTime = __Infer<typeof PlayerDayTime>;

export const PlayerNet = __t.object("PlayerNet", {
  identity: __t.identity(),
  reports: __t.u32(),
  lastP50: __t.u16(),
  lastP95: __t.u16(),
  avgP50: __t.f32(),
  avgP95: __t.f32(),
  worstP95: __t.u16(),
  corrections: __t.u32(),
  measuredSeconds: __t.u32(),
  lastAt: __t.timestamp(),
});
export type PlayerNet = __Infer<typeof PlayerNet>;

export const PlayerSeen = __t.object("PlayerSeen", {
  identity: __t.identity(),
  firstSeen: __t.timestamp(),
  lastSeen: __t.timestamp(),
  sessions: __t.u32(),
  tz: __t.string(),
  lang: __t.string(),
  name: __t.string(),
});
export type PlayerSeen = __Infer<typeof PlayerSeen>;

export const PlayerTime = __t.object("PlayerTime", {
  identity: __t.identity(),
  playSeconds: __t.u64(),
  since: __t.u64(),
});
export type PlayerTime = __Infer<typeof PlayerTime>;

export const Point = __t.object("Point", {
  id: __t.string(),
  progress: __t.f32(),
  owner: __t.i8(),
  contested: __t.bool(),
  capturing: __t.i8(),
});
export type Point = __Infer<typeof Point>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  name: __t.string(),
  kills: __t.u32(),
  deaths: __t.u32(),
  assists: __t.u32(),
  headshots: __t.u32(),
  roundsWon: __t.u32(),
  roundsPlayed: __t.u32(),
  matchesWon: __t.u32(),
  matchesPlayed: __t.u32(),
});
export type Profile = __Infer<typeof Profile>;

export const Roster = __t.object("Roster", {
  id: __t.u32(),
  room: __t.u8(),
  name: __t.string(),
  team: __t.u8(),
  bot: __t.bool(),
  alive: __t.bool(),
  grenades: __t.u8(),
  grenadeHe: __t.bool(),
  kills: __t.u32(),
  deaths: __t.u32(),
  assists: __t.u32(),
  score: __t.u32(),
  lastAttacker: __t.i32(),
  corrections: __t.u32(),
  weapon0: __t.string(),
  weapon1: __t.string(),
  reserve0: __t.u16(),
  reserve1: __t.u16(),
  money: __t.u32(),
  gearJson: __t.string(),
});
export type Roster = __Infer<typeof Roster>;

export const Soldier = __t.object("Soldier", {
  id: __t.u32(),
  name: __t.string(),
  team: __t.u8(),
  bot: __t.bool(),
  loadout: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  crouch: __t.f32(),
  grounded: __t.bool(),
  slideTime: __t.f32(),
  slideCooldown: __t.f32(),
  airTime: __t.f32(),
  prevCrouch: __t.bool(),
  prevJump: __t.bool(),
  alive: __t.bool(),
  health: __t.f32(),
  shield: __t.f32(),
  weapon: __t.u8(),
  ammo0: __t.u16(),
  ammo1: __t.u16(),
  reloadLeft: __t.f32(),
  fireCooldown: __t.f32(),
  switchLeft: __t.f32(),
  grenades: __t.u8(),
  respawnLeft: __t.f32(),
  protectLeft: __t.f32(),
  sinceHit: __t.f32(),
  lastAttacker: __t.i32(),
  kills: __t.u32(),
  deaths: __t.u32(),
  score: __t.u32(),
  captures: __t.u32(),
  lawCooldown: __t.f32(),
  sprint: __t.bool(),
  ads: __t.bool(),
  sinceShot: __t.f32(),
  corrections: __t.u32(),
  idle: __t.f32(),
  moveSlack: __t.f32(),
  groundY: __t.f32(),
  weapon0: __t.string(),
  weapon1: __t.string(),
  reserve0: __t.u16(),
  reserve1: __t.u16(),
  money: __t.u32(),
  bought0: __t.string(),
  bought1: __t.string(),
  sinceSpawn: __t.f32(),
  gearJson: __t.string(),
  room: __t.u8(),
});
export type Soldier = __Infer<typeof Soldier>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  room: __t.u8(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Vehicle = __t.object("Vehicle", {
  key: __t.u32(),
  room: __t.u8(),
  id: __t.u8(),
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  steer: __t.f32(),
  rotor: __t.f32(),
  grounded: __t.bool(),
  health: __t.f32(),
  driver: __t.i32(),
  passenger: __t.i32(),
  wrecked: __t.bool(),
  slack: __t.f32(),
  lastAttacker: __t.i32(),
  lastRun: __t.f64(),
});
export type Vehicle = __Infer<typeof Vehicle>;

export const VehicleInbox = __t.object("VehicleInbox", {
  soldierId: __t.u32(),
  vehicle: __t.u8(),
  lastMicros: __t.u64(),
  elapsed: __t.f32(),
  pending: __t.bool(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  aimYaw: __t.f32(),
  aimPitch: __t.f32(),
});
export type VehicleInbox = __Infer<typeof VehicleInbox>;

