// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  vehicle: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  aimYaw: __t.f32(),
  aimPitch: __t.f32(),
};
