// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminLoginReducer from "../admin_login_reducer";
import AdminLogoutReducer from "../admin_logout_reducer";
import AdminRevokeAllReducer from "../admin_revoke_all_reducer";
import BuyReducer from "../buy_reducer";
import BuyAttachmentReducer from "../buy_attachment_reducer";
import ChangeTeamReducer from "../change_team_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeviceReducer from "../device_reducer";
import DrinkReducer from "../drink_reducer";
import EnterVehicleReducer from "../enter_vehicle_reducer";
import ExitVehicleReducer from "../exit_vehicle_reducer";
import FireReducer from "../fire_reducer";
import GrenadeReducer from "../grenade_reducer";
import HelloReducer from "../hello_reducer";
import JoinReducer from "../join_reducer";
import JoinPublicReducer from "../join_public_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveReducer from "../leave_reducer";
import NetStatsReducer from "../net_stats_reducer";
import QuickAnyReducer from "../quick_any_reducer";
import QuickJoinReducer from "../quick_join_reducer";
import QuickPlayReducer from "../quick_play_reducer";
import ReloadWeaponReducer from "../reload_weapon_reducer";
import ReportReducer from "../report_reducer";
import SayReducer from "../say_reducer";
import SmokeReducer from "../smoke_reducer";
import StartRoomReducer from "../start_room_reducer";
import SwitchSlotReducer from "../switch_slot_reducer";
import UseCrateReducer from "../use_crate_reducer";
import VehicleReportReducer from "../vehicle_report_reducer";

export type AdminLoginParams = __Infer<typeof AdminLoginReducer>;
export type AdminLogoutParams = __Infer<typeof AdminLogoutReducer>;
export type AdminRevokeAllParams = __Infer<typeof AdminRevokeAllReducer>;
export type BuyParams = __Infer<typeof BuyReducer>;
export type BuyAttachmentParams = __Infer<typeof BuyAttachmentReducer>;
export type ChangeTeamParams = __Infer<typeof ChangeTeamReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeviceParams = __Infer<typeof DeviceReducer>;
export type DrinkParams = __Infer<typeof DrinkReducer>;
export type EnterVehicleParams = __Infer<typeof EnterVehicleReducer>;
export type ExitVehicleParams = __Infer<typeof ExitVehicleReducer>;
export type FireParams = __Infer<typeof FireReducer>;
export type GrenadeParams = __Infer<typeof GrenadeReducer>;
export type HelloParams = __Infer<typeof HelloReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type JoinPublicParams = __Infer<typeof JoinPublicReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type NetStatsParams = __Infer<typeof NetStatsReducer>;
export type QuickAnyParams = __Infer<typeof QuickAnyReducer>;
export type QuickJoinParams = __Infer<typeof QuickJoinReducer>;
export type QuickPlayParams = __Infer<typeof QuickPlayReducer>;
export type ReloadWeaponParams = __Infer<typeof ReloadWeaponReducer>;
export type ReportParams = __Infer<typeof ReportReducer>;
export type SayParams = __Infer<typeof SayReducer>;
export type SmokeParams = __Infer<typeof SmokeReducer>;
export type StartRoomParams = __Infer<typeof StartRoomReducer>;
export type SwitchSlotParams = __Infer<typeof SwitchSlotReducer>;
export type UseCrateParams = __Infer<typeof UseCrateReducer>;
export type VehicleReportParams = __Infer<typeof VehicleReportReducer>;

