// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuyReducer from "../buy_reducer";
import BuyAttachmentReducer from "../buy_attachment_reducer";
import CreateRoomReducer from "../create_room_reducer";
import EnterVehicleReducer from "../enter_vehicle_reducer";
import ExitVehicleReducer from "../exit_vehicle_reducer";
import FireReducer from "../fire_reducer";
import GrenadeReducer from "../grenade_reducer";
import JoinReducer from "../join_reducer";
import JoinPublicReducer from "../join_public_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveReducer from "../leave_reducer";
import QuickJoinReducer from "../quick_join_reducer";
import ReloadWeaponReducer from "../reload_weapon_reducer";
import ReportReducer from "../report_reducer";
import SayReducer from "../say_reducer";
import SwitchSlotReducer from "../switch_slot_reducer";
import UseCrateReducer from "../use_crate_reducer";
import VehicleReportReducer from "../vehicle_report_reducer";

export type BuyParams = __Infer<typeof BuyReducer>;
export type BuyAttachmentParams = __Infer<typeof BuyAttachmentReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EnterVehicleParams = __Infer<typeof EnterVehicleReducer>;
export type ExitVehicleParams = __Infer<typeof ExitVehicleReducer>;
export type FireParams = __Infer<typeof FireReducer>;
export type GrenadeParams = __Infer<typeof GrenadeReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type JoinPublicParams = __Infer<typeof JoinPublicReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type QuickJoinParams = __Infer<typeof QuickJoinReducer>;
export type ReloadWeaponParams = __Infer<typeof ReloadWeaponReducer>;
export type ReportParams = __Infer<typeof ReportReducer>;
export type SayParams = __Infer<typeof SayReducer>;
export type SwitchSlotParams = __Infer<typeof SwitchSlotReducer>;
export type UseCrateParams = __Infer<typeof UseCrateReducer>;
export type VehicleReportParams = __Infer<typeof VehicleReportReducer>;

